apiVersion: v1
kind: Service
metadata:
  name: openx
  namespace: default
spec:
  selector:
    app: openx
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openx
  template:
    metadata:
      labels:
        app: openx
    spec:
      containers:
        - name: openx
          image: varunramg/openx:latest
          ports:
            - containerPort: 8080
          env:
            - name: OPENX_PORT
              value: 8080
            - name: OPENX_INSECURE
              value: false
            - name: OPENX_MAINNET
              value: false
          imagePullPolicy: Always